-- MySQL Script generated by MySQL Workbench
-- Mon Feb 17 08:52:01 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
 
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
 
-- -----------------------------------------------------
-- Schema darazsj_cimexplore
-- -----------------------------------------------------
 
-- -----------------------------------------------------
-- Schema darazsj_cimexplore
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `darazsj_cimexplore` DEFAULT CHARACTER SET utf8 ;
USE `darazsj_cimexplore` ;
 
-- -----------------------------------------------------
-- Table `darazsj_cimexplore`.`T_Utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `darazsj_cimexplore`.`T_Utilisateur` (
  `PK_utilisateur` INT NOT NULL AUTO_INCREMENT,
  `user` VARCHAR(200) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `isAdmin` TINYINT NOT NULL,
  PRIMARY KEY (`PK_utilisateur`))
ENGINE = InnoDB;
 
 
-- -----------------------------------------------------
-- Table `darazsj_cimexplore`.`T_Categorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `darazsj_cimexplore`.`T_Categorie` (
  `PK_Categorie` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`PK_Categorie`))
ENGINE = InnoDB;
 
 
-- -----------------------------------------------------
-- Table `darazsj_cimexplore`.`T_marque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `darazsj_cimexplore`.`T_marque` (
  `PK_marque` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`PK_marque`))
ENGINE = InnoDB;
 
 
-- -----------------------------------------------------
-- Table `darazsj_cimexplore`.`T_Produit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `darazsj_cimexplore`.`T_Produit` (
  `PK_produit` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(50) NOT NULL,
  `description` VARCHAR(500) NOT NULL,
  `lien_Image` VARCHAR(500) NOT NULL,
  `prix` DECIMAL(10, 2) NOT NULL,  -- Prix en décimal avec 2 décimales
  `FK_Categorie` INT NOT NULL,
  `FK_Marque` INT NOT NULL,
  PRIMARY KEY (`PK_produit`),
  INDEX `fk_T_Produit_T_Categorie1_idx` (`FK_Categorie` ASC) VISIBLE,
  INDEX `fk_T_Produit_T_marque1_idx` (`FK_Marque` ASC) VISIBLE,
  CONSTRAINT `fk_T_Produit_T_Categorie1`
    FOREIGN KEY (`FK_Categorie`)
    REFERENCES `darazsj_cimexplore`.`T_Categorie` (`PK_Categorie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_T_Produit_T_marque1`
    FOREIGN KEY (`FK_Marque`)
    REFERENCES `darazsj_cimexplore`.`T_marque` (`PK_marque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
 
 
-- -----------------------------------------------------
-- Table `darazsj_cimexplore`.`T_Utilisateur_has_T_Produit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `darazsj_cimexplore`.`T_Utilisateur_has_T_Produit` (
  `FK_Utilisateur` INT NOT NULL,
  `FK_Produit` INT NOT NULL,
  PRIMARY KEY (`FK_Utilisateur`, `FK_Produit`),
  INDEX `fk_T_Utilisateur_has_T_Produit_T_Produit1_idx` (`FK_Produit` ASC) VISIBLE,
  INDEX `fk_T_Utilisateur_has_T_Produit_T_Utilisateur1_idx` (`FK_Utilisateur` ASC) VISIBLE,
  CONSTRAINT `fk_T_Utilisateur_has_T_Produit_T_Utilisateur1`
    FOREIGN KEY (`FK_Utilisateur`)
    REFERENCES `darazsj_cimexplore`.`T_Utilisateur` (`PK_utilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_T_Utilisateur_has_T_Produit_T_Produit1`
    FOREIGN KEY (`FK_Produit`)
    REFERENCES `darazsj_cimexplore`.`T_Produit` (`PK_produit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
 
 
SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
 
INSERT INTO `darazsj_cimexplore`.`T_marque` (`nom`) VALUES
('Black Diamond'),
('La Sportiva'),
('Mammut'),
('Salomon'),
('Petzl'),
('Scarpa'),
('The North Face'),
('Arcteryx'),
('Columbia'),
('Rossignol');
 
INSERT INTO `darazsj_cimexplore`.`T_Categorie` (`nom`) VALUES
('Crampons'),
('Piolets'),
('Cordes'),
('Chaussures'),
('Vestes'),
('Tentes'),
('Sacs'),
('Lampes'),
('Gants'),
('Ski');
 
 
INSERT INTO `darazsj_cimexplore`.`T_Produit` (`nom`, `description`, `lien_Image`, `prix`, `FK_Categorie`, `FK_Marque`) VALUES
-- Produit 1
('Crampons Black Diamond', 'Crampons pour alpinisme, idéal pour les conditions glacées.', 'https://www.hajk.ch/media/catalog/product/cache/035497cfd5d0f0446ffaf4bc7341e997/2/0/20514_contact-strap-crampons_no-color_01_-_1_.jpg', 150.00, 1, 1), -- Categorie: Crampons, Marque: Black Diamond
 
-- Produit 2
('Piolet Petzl', 'Piolet léger et robuste, conçu pour les ascensions techniques.', 'https://images.snowleader.com/cdn-cgi/image/f=auto,fit=scale-down,q=85/https://images.snowleader.com/media/catalog/product/cache/1/image/0dc2d03fe217f8c83829496872af24a0/P/E/PETZ00184_01.jpg', 120.50, 2, 5), -- Categorie: Piolets, Marque: Petzl
 
-- Produit 3
('Cordes Mammut', 'Cordes de haute qualité pour l’escalade et l’alpinisme.', 'https://dawfo2ydqeykk.cloudfront.net/catalog/product/2/0/2010-04340-01231_main-min_1-min.jpg?width=500&height=500&store=fr&image-type=image', 200.75, 3, 3), -- Categorie: Cordes, Marque: Mammut
 
-- Produit 4
('Chaussures La Sportiva', 'Chaussures de montagne haut de gamme avec une excellente adhérence.', 'https://www.urechlyss.ch/thumbnail/a4/51/67/1713533482/432953-000-la-sportiva-bergschuh-nepal-evo-gtx_1920x1920.webp', 180.25, 4, 2), -- Categorie: Chaussures, Marque: La Sportiva
 
-- Produit 5
('Veste The North Face', 'Veste imperméable et respirante pour les conditions extrêmes.', 'https://doodah.ch/media/catalog/product/cache/3055883bd7b9914052e516e09314f7e2/n/f/nf0a5j55kx7-the-north-face-m-2000-mountain-jacket-tnf-black-tnf-black_01.jpg', 250.99, 5, 7), -- Categorie: Vestes, Marque: The North Face
 
-- Produit 6
('Tente Arcteryx', 'Tente légère, résistante au vent et facile à monter.', 'https://images.snowleader.com/cdn-cgi/image/f=auto,fit=scale-down,q=85/https://images.snowleader.com/media/catalog/product/cache/1/image/0dc2d03fe217f8c83829496872af24a0/l/i/lightent_3_pro_tent_olive_green-simple-ferrino-ferr00381_3_1.jpg', 400.00, 6, 8), -- Categorie: Tentes, Marque: Arcteryx
 
-- Produit 7
('Sac à dos Columbia', 'Sac à dos avec système de ventilation et compartiment pour hydratation.', 'https://www.bfgcdn.com/600_600_90/506-0187/columbia-maxtrail-22l-sac-a-dos-dhydratation.jpg', 90.00, 7, 9), -- Categorie: Sacs, Marque: Columbia
 
-- Produit 8
('Lampe frontale Black Diamond', 'Lampe frontale ultra lumineuse pour les randonnées nocturnes.', 'https://images.snowleader.com/cdn-cgi/image/f=auto,fit=scale-down,q=85/https://images.snowleader.com/media/catalog/product/cache/1/image/0dc2d03fe217f8c83829496872af24a0/o/n/onsight_375_headlamp_octane-simple-blackdiamo-blad01760_1.jpg', 45.75, 8, 1), -- Categorie: Lampes, Marque: Black Diamond
 
-- Produit 9
('Gants Salomon', 'Gants isolants et imperméables, parfaits pour l’alpinisme.', 'https://images.snowleader.com/cdn-cgi/image/f=auto,fit=scale-down,q=85/https://images.snowleader.com/media/catalog/product/cache/1/image/0dc2d03fe217f8c83829496872af24a0/S/A/SALO09064_01_202407120559.jpg', 70.50, 9, 4), -- Categorie: Gants, Marque: Salomon
 
-- Produit 10
('Ski Rossignol', 'Skis polyvalents pour la montagne, adaptés à tous les niveaux.', 'https://images.snowleader.com/cdn-cgi/image/f=auto,fit=scale-down,q=85/https://images.snowleader.com/media/catalog/product/cache/1/image/0dc2d03fe217f8c83829496872af24a0/R/O/ROSS02735_01_202408130447.jpg', 550.00, 10, 10); -- Categorie: Ski, Marque: Rossignol
 
INSERT INTO `darazsj_cimexplore`.`T_Utilisateur` (user, password, isAdmin) VALUES
('user', '$2y$10$bjCyHzlHRbNk1oINT5oZC.IKEo1iSFXDilWiqcz9QuM2.BajL/CBq', 0),
('robert', '$2y$10$bjCyHzlHRbNk1oINT5oZC.IKEo1iSFXDilWiqcz9QuM2.BajL/CBq', 0),
('admin', '$2y$10$bjCyHzlHRbNk1oINT5oZC.IKEo1iSFXDilWiqcz9QuM2.BajL/CBq', 1);